# Generated by Django 5.0.7 on 2024-07-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=4)),
                ("student_ID", models.CharField(max_length=10)),
                ("question1", models.TextField()),
                ("question2", models.TextField()),
                ("question3", models.TextField()),
            ],
        ),
    ]
