# Generated by Django 5.0.7 on 2024-07-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_questionnaire"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="mood",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="question2",
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="instagram",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="line_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="trait1",
            field=models.CharField(default=45, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="trait2",
            field=models.CharField(default=45, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="trait3",
            field=models.CharField(default=45, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="question1",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="question3",
            field=models.TextField(max_length=20),
        ),
        migrations.DeleteModel(
            name="Mood",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
