# Generated by Django 5.0.7 on 2024-07-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0003_remove_post_mood_remove_questionnaire_question2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnaire",
            name="instagram",
            field=models.CharField(default="##########", max_length=20),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="line_id",
            field=models.CharField(default="##########", max_length=20),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="question1",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="question3",
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="trait1",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="trait2",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="trait3",
            field=models.CharField(max_length=10),
        ),
    ]
