# Generated by Django 3.0.5 on 2024-07-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_questionnaire_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
